### ISSUE TITLE
White pages with php7.2 (nginx)

### ISSUE THREAD

**Issue by ProJaCore** [cydrobolt/polr#428]
I did setup all the requested stuff and even if the installation guide is not really working out. 
But at the end i (half)/installed polr via composer and did all the typical migration laravel stuff.
I did Composer install --no-dev -o
and i did migrate --force
and there was another cleanup command.

But for any reason i get white pages and that was the reason why i couldnt setup the installation via /setup/. i did it manually.

## Current Behavior
The routing works fine; ill get forwarded from /login to /admin and etc.
But i am getting white pages only.
I also reinstalled it 3 times now. 

even with debug mode on i couldnt find any other error than this:
```
[2018-03-28] lumen.ERROR: InvalidArgumentException: Command "php" is not defined. in /var/www/mysite.com/www/vendor/symfony/console/Application.php:515
Stack trace:
#0 /var/www/mysite.com/www/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->find('php')
#1 /var/www/mysite.com/www/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/mysite.com/www/vendor/laravel/lumen-framework/src/Console/Kernel.php(78): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/mysite.com/www/artisan(35): Laravel\Lumen\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 {main}
```

## Your Environment
* commit:  a243a87
* Environment: PHP7.2,nginx, a huge root server.

**Comment by ricopags** [comment]
What happens if you type php -v on the command line?

Try any of these fixes?

https://stackoverflow.com/questions/35261746/laravel-error-invalidargumentexception/39635075

I'm no expert so if this is terrifically unrelated I'm sorry. Just a fan of the project and trying to help.

**Comment by overint** [comment]
I'm going to guess that error is from you typing `php artisan php ...`
Could you check your apache/nginx error log for errors?

**Comment by ProJaCore** [comment]
well i didnt type php artisan php
but im going to try if the error is realted to it.

**Comment by ProJaCore** [comment]
Oh okay. i found the bug. I had a wrong logging configuration; that was the reason why i did not recieve any logs.
And i got this error:
```
*1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/mysite.com/www/storage/logs/lumen.log" could not be opened: failed to open stream: Permission denied in /var/www/mysite.com/www/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
Stack trace:
#0 /var/www/mysite.com/www/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array)
#1 /var/www/mysite.com/www/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /var/www/mysite.com/www/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\Logger->addRecord(400, Object(UnexpectedValueException), Array)
#3 /var/www/mysite.com/www/vendor/laravel/lumen-framework/src/Exceptions/Handler.php(38): Monolog\Logger->error(Object(UnexpectedValueException))
#4 /var/www/mysite.com/www/app/Exceptions/Handler.php(33): Laravel\Lumen\Exceptions\Handler->report(Object(UnexpectedValueException))
#5 /var/www/mysite.com/www/...
PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/mysite.com/www/storage/logs/lumen.log" could not be opened: failed to open stream: Permission denied in /var/www/mysite.com/www/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
Stack trace:
#0 /var/www/mysite.com/www/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array)
#1 /var/www/mysite.com/www/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /var/www/mysite.com/www/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\Logger->addRecord(400, Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#3 /var/www/mysite.com/www/vendor/laravel/lumen-framework/src/Exceptions/Handler.php(38): Monolog\Logger->error(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 /var/www/mysite.com/www/app/Exc
```
i didnt chown the folder properly. now its working!

**Comment by cydrobolt** [comment]
Awesome!

**Comment by tjhunkin** [comment]
@ProJaCore Do you remember what you changed? I seem to have the same error, but I can't pinpoint where it's originating from

**Comment by ProJaCore** [comment]
@tjhunkin  Well i did chown the respected folders! Its about 2 years ago (unbelievable) and i can't really   remember either unfortunately.

**Comment by SuperlativeEntity** [comment]
Thanks for the reply. This only started on my side after upgrading from php 7.1 to php7.2. The permissions on my folders are correct. Very odd. I also checked all crons, supervisor configs and the scheduled commands to see if anything is adding an extra php string into a command to no avail.

**Comment by ProJaCore** [comment]
@SuperlativeEntity  I guess that the php session runs with an different user than the original user. if you're running linux compare your old php-fpm.conf from 7.2 with the one from 7.3 . It should have the same user. Otherwise check what username php is running under and check if the respective folders and files have the same user "chowned".

**Comment by SuperlativeEntity** [comment]
Thanks, will have a look
