### ISSUE TITLE
Upgrading to php8.0 results in "Whoops, looks like something went wrong."

### ISSUE THREAD

**Issue by bdemirci** [cydrobolt/polr#590]
## Expected Behavior

I expect the login page, or any page, to load

## Current Behavior

"Whoops, looks like something went wrong."

## Possible Solution

./storage/logs/lumen.log states:

[2021-02-21 18:58:17] lumen.ERROR: ErrorException: Method ReflectionParameter::getClass() is deprecated in /var/www/example.com/vendor/illuminate/container/Container.php:795
Stack trace:
#0 /var/www/example.com/vendor/illuminate/container/Container.php(795): Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#1 /var/www/example.com/vendor/illuminate/container/Container.php(775): Illuminate\Container\Container->getDependencies()
#2 /var/www/example.com/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build()
#3 /var/www/example.com/vendor/laravel/lumen-framework/src/Application.php(447): Illuminate\Container\Container->make()
#4 /var/www/example.com/vendor/illuminate/pipeline/Pipeline.php(123): Laravel\Lumen\Application->make()
#5 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#6 /var/www/example.com/vendor/illuminate/pipeline/Pipeline.php(102): call_user_func()
#7 /var/www/example.com/vendor/laravel/lumen-framework/src/Application.php(1451): Illuminate\Pipeline\Pipeline->then()
#8 /var/www/example.com/vendor/laravel/lumen-framework/src/Application.php(1221): Laravel\Lumen\Application->sendThroughPipeline()
#9 /var/www/example.com/vendor/laravel/lumen-framework/src/Application.php(1161): Laravel\Lumen\Application->dispatch()
#10 /var/www/example.com/public/index.php(28): Laravel\Lumen\Application->run()
#11 {main}
[2021-02-21 18:58:17] lumen.ERROR: ErrorException: Method ReflectionParameter::getClass() is deprecated in /var/www/example.com/vendor/illuminate/container/Container.php:795
Stack trace:
#0 /var/www/example.com/vendor/illuminate/container/Container.php(795): Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#1 /var/www/example.com/vendor/illuminate/container/Container.php(775): Illuminate\Container\Container->getDependencies()
#2 /var/www/example.com/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build()
#3 /var/www/example.com/vendor/laravel/lumen-framework/src/Application.php(447): Illuminate\Container\Container->make()
#4 /var/www/example.com/vendor/laravel/lumen-framework/src/Application.php(1185): Laravel\Lumen\Application->make()
#5 /var/www/example.com/vendor/laravel/lumen-framework/src/Application.php(1170): Laravel\Lumen\Application->callTerminableMiddleware()
#6 /var/www/example.com/public/index.php(28): Laravel\Lumen\Application->run()
#7 {main}

## Steps to Reproduce (for bugs)

1. Install Polr with php5/7
2. Upgrade to php8.0
3. Restart webserver

## Your Environment

* Version or latest commit hash (`git rev-parse HEAD`):
* Environment name and version (e.g. Chrome 39, PHP 7.0, etc): Firefox 85.0.2, PHP 8.0, Apache2
* Instance link (optional):

**Comment by mehdiMj-ir** [comment]
bro we have same problem, why they don't consider checking #591 :(
