### ISSUE TITLE
Polr fails to render in php8 due to fatal error

### ISSUE THREAD

**Issue by fleish** [Cydrobolt/polr#639]
## Expected Behavior

Polr code should render and pages should load

## Current Behavior

Polr code fails due to PHP fatal error

## Steps to Reproduce (for bugs)
1. Upgrade from php7.4 (PHP Version 7.4.3-4ubuntu2.19) to php8.3 (PHP Version 8.3.2-1+ubuntu20.04.1+deb.sury.org+1)
2. Attempt to load polr in web browser
3. Observe php fatal error in logs and page does not render

From trying to load /:
```2024/01/21 21:34:20 [error] 24186#24186: *20 FastCGI sent in stderr: "PHP message: PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Config\Repository::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/polr/vendor/illuminate/config/Repository.php:118
Stack trace:
#0 /var/www/html/polr/vendor/illuminate/config/Repository.php(9): Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#1 /var/www/html/polr/vendor/composer/ClassLoader.php(444): include('...')
#2 /var/www/html/polr/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 /var/www/html/polr/vendor/laravel/lumen-framework/src/Application.php(524): Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/html/polr/vendor/illuminate/container/Container.php(738): Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#5 /var/www/html/polr/vendor/illuminate/container/Container.php(631): Illu...; PHP message: PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Http\Request::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/polr/vendor/illuminate/http/Request.php:850
Stack trace:
#0 /var/www/html/polr/vendor/illuminate/http/Request.php(14): Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#1 /var/www/html/polr/vendor/composer/ClassLoader.php(444): include('...')
#2 /var/www/html/polr/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 /var/www/html/polr/vendor/laravel/lumen-framework/src/Application.php(712): Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/html/polr/vendor/illuminate/container/Container.php(738): Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#5 /var/www/html/polr/vendor/illu
2024/01/21 21:34:20 [error] 24186#24186: *20 FastCGI sent in stderr: "PHP message: PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Config\Repository::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/polr/vendor/illuminate/config/Repository.php:118
Stack trace:
#0 /var/www/html/polr/vendor/illuminate/config/Repository.php(9): Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#1 /var/www/html/polr/vendor/composer/ClassLoader.php(444): include('...')
#2 /var/www/html/polr/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 /var/www/html/polr/vendor/laravel/lumen-framework/src/Application.php(524): Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/html/polr/vendor/illuminate/container/Container.php(738): Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#5 /var/www/html/polr/vendor/illuminate/container/Container.php(631): Illu...; PHP message: PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Http\Request::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/polr/vendor/illuminate/http/Request.php:850
Stack trace:
#0 /var/www/html/polr/vendor/illuminate/http/Request.php(14): Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#1 /var/www/html/polr/vendor/composer/ClassLoader.php(444): include('...')
#2 /var/www/html/polr/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 /var/www/html/polr/vendor/laravel/lumen-framework/src/Application.php(712): Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/html/polr/vendor/illuminate/container/Container.php(738): Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#5 /var/www/html/polr/vendor/illu
```

From trying to load /login
```
2024/01/21 21:34:24 [error] 24186#24186: *20 FastCGI sent in stderr: "PHP message: PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Config\Repository::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/polr/vendor/illuminate/config/Repository.php:118
Stack trace:
#0 /var/www/html/polr/vendor/illuminate/config/Repository.php(9): Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#1 /var/www/html/polr/vendor/composer/ClassLoader.php(444): include('...')
#2 /var/www/html/polr/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 /var/www/html/polr/vendor/laravel/lumen-framework/src/Application.php(524): Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/html/polr/vendor/illuminate/container/Container.php(738): Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#5 /var/www/html/polr/vendor/illuminate/container/Container.php(631): Illu...; PHP message: PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Http\Request::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/polr/vendor/illuminate/http/Request.php:850
Stack trace:
#0 /var/www/html/polr/vendor/illuminate/http/Request.php(14): Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#1 /var/www/html/polr/vendor/composer/ClassLoader.php(444): include('...')
#2 /var/www/html/polr/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 /var/www/html/polr/vendor/laravel/lumen-framework/src/Application.php(712): Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/html/polr/vendor/illuminate/container/Container.php(738): Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#5 /var/www/html/polr/vendor/illu
```

## Context

Trying to keep system code up to date

## Your Environment
* Version or latest commit hash (`git rev-parse HEAD`):
2.3.0b downloaded from github releases page

* Environment name and version (e.g. Chrome 39, PHP 7.0, etc):
Ubuntu server running Focal 20.04LTS (same issue persists upon upgrade to Jammy 22.04LTS)
NGINX (nginx version: nginx/1.18.0 (Ubuntu))
PHP 8.3 (PHP Version 8.3.2-1+ubuntu20.04.1+deb.sury.org+1)

**Comment by fleish** [comment]
@cydrobolt any chance you could take a look at this? I just got bit by it again when I blindly ran an apt autoremove which pulled the php7.4 packages in favor of php8.3. I restored php7.4 to fix, but since that's been EOL since November 2022 it would be great to be able to upgrade and still have polr be functional. Thanks in advance.

**Comment by redlukas** [comment]
running into the same issues, compatibility with PHP > 8 would be greatly appreciated

**Comment by fleish** [comment]
I didn't see it before, but [this fork](https://github.com/Antelope-Valley-College/polr) from @mwilmes-at-avc mentioned [here](https://github.com/cydrobolt/polr/issues/626#issuecomment-1355729318) sounds promising:

EDIT: confirmed it's working for me in Ubuntu 22.04LTS with PHP 8.4.18

I had to restore `public/css/bootswatch/3.3.7` to get my dark mode account preference to work (and fix the page layout presumably thrown off as a result of it's absence) but the core functionality worked fine without it
